### ISSUE TITLE
Cyrillic popup menu - not shown

### ISSUE THREAD

**Issue by D1mon** [neoclide/coc-lists#27] opened 2019-06-11 11:48 UTC
autocomplete works, no popup menu is displayed in current buffer:
https://www.dropbox.com/s/4kipjaef6fzuzil/2019-06-11%2014-33-00.mkv?dl=0

**Comment by chemzqm** [comment] 2019-06-11 12:16
Can't reproduce.

**Comment by D1mon** [comment] 2019-06-11 12:21
do you work? maybe there is a problem in the settings?

**Comment by chemzqm** [comment] 2019-06-11 12:24
I have reproduced.

**Comment by chemzqm** [comment] 2019-06-11 12:48
Fixed on master of coc.nvim.

**Closed by chemzqm** 2019-06-11 12:48 UTC

**Comment by D1mon** [comment] 2019-06-11 13:00
Thank you!
